---
- hosts: localhost
  tasks:
  - name: Remove droplet
    digital_ocean:
      state: absent
      command: droplet
      name: controller-0
      api_token: "{{ digital_ocean_api_token }}"
      unique_name: yes
  - name: Remove droplet
    digital_ocean:
      state: absent
      command: droplet
      name: worker-0
      api_token: "{{ digital_ocean_api_token }}"
      unique_name: yes
  - name: Remove droplet
    digital_ocean:
      state: absent
      command: droplet
      name: worker-1
      api_token: "{{ digital_ocean_api_token }}"
      unique_name: yes
  - name: Remove droplet
    digital_ocean:
      state: absent
      command: droplet
      name: worker-2
      api_token: "{{ digital_ocean_api_token }}"
      unique_name: yes

